name: 2.13.1.$(Rev:r)

trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK 3.1.103'
    inputs:
      packageType: sdk
      version: 3.1.103
      installationPath: $(Agent.ToolsDirectory)/dotnet
    
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build

  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: pack
      packagesToPack: '**/Pulumi.FSharp.Aws.fsproj'
      versioningScheme: byBuildNumber

  - task: NuGetCommand@2
    displayName: Push
    inputs:
      command: push
      packagesToPush: '$(Build.ArtifactStagingDirectory)/Pulumi.FSharp.Aws.2.13.1.*.nupkg'
      nuGetFeedType: external
      publishFeedCredentials: NuGet