name: $(Rev:r)

# Set the pipeline variable `provider` to a provider E.G. `Azure` `AzureAD` `Aws` `Kubernetes`

# Create a secure file `Pulumi.FSharp.Extensions.vault.json`
# with the following content:
# {
#   "values": [
#     {
#       "secret": false,
#       "value": "<NuGet API key>",
#       "name": "nuGetApiKey"
#     }
#   ]
# }

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - Pulumi.FSharp.Myriad/*

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: Install FAKE
  inputs:
    command: custom
    custom: tool
    arguments: install fake-cli

- task: DownloadSecureFile@1
  name: FakeVaultFile
  displayName: Download FAKE Vault file
  inputs:
    secureFile: Pulumi.FSharp.Extensions.vault.json

- task: DotNetCoreCLI@2
  displayName: Run FAKE
  inputs:
    command: custom
    custom: fake
    arguments: run