name: $(Rev:r)

# Set the pipeline variable `provider` to a provider E.G. `Azure` `AzureAD` `Aws` `Kubernetes`

variables:
# Create a variable group called NuGet
# and add the variable `apiKey`
- group: NuGet

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - Pulumi.FSharp.Myriad/*
      - Pulumi.FSharp.$(provider)/*

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: Install FAKE
  inputs:
    command: custom
    custom: tool
    arguments: install fake-cli

- task: DotNetCoreCLI@2
  displayName: Run FAKE
  inputs:
    command: custom
    custom: fake
    arguments: run