name: $(Rev:r)

parameters:
  - name: provider
    type: string
    default: $(pipeline-provider)

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - Pulumi.FSharp.Myriad/*
      - Pulumi.FSharp.$(pipeline-provider)/*

pool:
  vmImage: ubuntu-latest

steps:
  - task: Bash@3
    displayName: Set provider version variable
    env:
      BUILD_NUMBER: $(Build.BuildNumber)
    inputs:
      targetType: inline
      script: |
        export PROJECT_FILE="Pulumi.FSharp.${{ parameters.provider }}/Pulumi.FSharp.${{ parameters.provider }}.fsproj"
        export NUGET_VERSION=$(grep -oP '<PackageReference Include=\"Pulumi.${{ parameters.provider }}\" Version=\"\K[0-9.]*' $PROJECT_FILE)
        # This is slow, ~30s on an hosted build agent
        #dotnet restore Pulumi.FSharp.${{ parameters.provider }}
        #export NUGET_VERSION=$(dotnet list Pulumi.FSharp.${{ parameters.provider }} package | grep -oP '${{ parameters.provider }}[ ]*\K[1-9][0-9.]*')
        echo "##vso[task.setvariable variable=providerVersion]${NUGET_VERSION}.${BUILD_NUMBER}"
    
  - task: UseDotNet@2
    displayName: Use .NET 5 SDK
    inputs:
      packageType: sdk
      version: 5.x
      installationPath: $(Agent.ToolsDirectory)/dotnet
    
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/Pulumi.FSharp.${{ parameters.provider }}.fsproj'

  - task: PublishBuildArtifacts@1
    displayName: Publish generated code
    inputs:
      pathToPublish: '**/Pulumi.FSharp.${{ parameters.provider }}/Generated.fs'

  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: pack
      packagesToPack: '**/Pulumi.FSharp.${{ parameters.provider }}.fsproj'
      versioningScheme: byEnvVar
      versionEnvVar: providerVersion

  - task: NuGetCommand@2
    displayName: Push
    inputs:
      command: push
      packagesToPush: $(Build.ArtifactStagingDirectory)/Pulumi.FSharp.${{ parameters.provider }}.$(providerVersion).nupkg
      nuGetFeedType: external
      publishFeedCredentials: NuGet