name: $(Rev:r)

variables:
  - name: provider
    value: Core

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - Pulumi.FSharp.Core/*

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseDotNet@2
    displayName: Use .NET 5 SDK
    inputs:
      packageType: sdk
      version: 5.x
      installationPath: $(Agent.ToolsDirectory)/dotnet
    
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/Pulumi.FSharp.$(provider).fsproj'

  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: pack
      packagesToPack: '**/Pulumi.FSharp.$(provider).fsproj'

  - task: NuGetCommand@2
    displayName: Push
    inputs:
      command: push
      packagesToPush: $(Build.ArtifactStagingDirectory)/Pulumi.FSharp.$(provider).*.nupkg
      nuGetFeedType: external
      publishFeedCredentials: NuGet