name: 3.46.0.$(Rev:r)

trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET 5 SDK'
    inputs:
      packageType: sdk
      version: 5.x
      installationPath: $(Agent.ToolsDirectory)/dotnet
    
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/Pulumi.FSharp.Azure.fsproj'

  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: pack
      packagesToPack: '**/Pulumi.FSharp.Azure.fsproj'
      versioningScheme: byBuildNumber

  - task: PublishBuildArtifacts@1
    displayName: Push
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/Pulumi.FSharp.Azure.3.46.0.*.nupkg'